module views.viva.views {
    requires javafx.controls;
    requires javafx.fxml;
    requires java.net.http;
    requires okhttp3;
    requires org.json;
    requires java.desktop;
    requires Bemathec;
    requires javafx.graphics;
    requires javafx.base;
    requires mysql.connector.j;
    requires static lombok;
    requires com.fasterxml.jackson.jr.ob;
    requires kernel;
    requires layout;
    requires com.google.gson;
    requires java.sql;
    requires com.fasterxml.jackson.databind;
    requires itextpdf;
    requires xmlworker;

    opens views.viva.views to javafx.fxml;
    exports views.viva.views;
    exports views.viva.views.Funcionalidades.API;
    opens views.viva.views.Funcionalidades.API to javafx.fxml;
    exports views.viva.views.Entidades.Evento.Controllers;
    opens views.viva.views.Entidades.Evento.Controllers to javafx.fxml;
    exports views.viva.views.Entidades.Vendedor.Controllers;
    opens views.viva.views.Entidades.Vendedor.Controllers to javafx.fxml;
    exports views.viva.views.Funcionalidades.Login.Controller;
    opens views.viva.views.Funcionalidades.Login.Controller to javafx.fxml;
    exports views.viva.views.Entidades.Evento.Model;
    opens views.viva.views.Entidades.Evento.Model to javafx.fxml;
    exports views.viva.views.Entidades.Transacao.Controllers;
    opens views.viva.views.Entidades.Transacao.Controllers to javafx.fxml;
    exports views.viva.views.Entidades.Operacoes.Model;
    opens views.viva.views.Entidades.Operacoes.Model to javafx.fxml;
    exports views.viva.views.Entidades.Transacao.Model;
    opens views.viva.views.Entidades.Transacao.Model to javafx.fxml;
    exports views.viva.views.Entidades.Vendedor.Model;
    opens views.viva.views.Entidades.Vendedor.Model to javafx.fxml;
    exports views.viva.views.Entidades.Cliente.Model;
    opens views.viva.views.Entidades.Cliente.Model to javafx.fxml;
    exports views.viva.views.Entidades.Operacoes.Controller;
    opens views.viva.views.Entidades.Operacoes.Controller to javafx.fxml;
    exports views.viva.views.Funcionalidades.Impressora to com.fasterxml.jackson.jr.ob;
    exports views.viva.views.Entidades.Relatorio.Controller;
    opens views.viva.views.Entidades.Relatorio.Controller to javafx.fxml;
    exports views.viva.views.Entidades.Relatorio.Service;
    opens views.viva.views.Entidades.Relatorio.Service to javafx.fxml;
}